//! The trace cases and their writer, shared by `examples/trace.rs` (which
//! writes the files) and `tests/traces.rs` (which compares them). No
//! library code: a case is a network built through the public API plus a
//! drive, and a row is what `step()` returned and `neurons()` after it.
//!
//! Format `neuralos-trace v1`, one file per case in this directory:
//!
//! ```text
//! # neuralos-trace v1 case=<name> kind=<regression|reference> n=<neurons> dt_us=<dt> res=<mV|cmV> plasticity=<on|off> divisor=<d> steps=<N> rows=<all|spikes>
//! <step> <time_us> | <spiking neuron ids> | <membrane of every neuron, i16 quanta>
//! ```
//!
//! One row per step (`rows=all`), or one per step that spiked
//! (`rows=spikes`; the board case is 10,000 steps and 147 rows). A row is
//! written after its step: `time_us` is the step's own timestamp, the one
//! its spikes carry; the ids are the spikes `step()` returned, in neuron
//! order, nothing between the bars when the step was silent; the
//! membranes are `neurons()` after the step, so a neuron that fired shows
//! its reset potential. Everything is decimal. Where a case keeps the
//! noise, it is the neuron's own LFSR, seeded by id and time, so every
//! case is a pure function of this file.
//!
//! Two words, two meanings (PR B). A `regression` trace comes from this
//! code and is compared with itself across commits: a trace that moves is
//! red, and a deliberate move is regenerated by
//! `cargo run -p neuralos-snn --example trace -- write` in a commit whose
//! message says which cases moved and why. A `reference` vector is also
//! checked against an oracle that is not this code: the unbounded-integer
//! neuron equation in `tests/traces.rs`. The only oracle today is that
//! neuron model, so there is one reference vector, a bare neuron with no
//! synapse and no spike.

use std::path::{Path, PathBuf};

use neuralos_snn::{LIFNeuron, NeuronType, SpikingNeuralNetwork, VoltageResolution};

/// The format line's name and version.
pub const FORMAT: &str = "neuralos-trace v1";
/// Where the files live: this directory, resolved from the crate root.
pub const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/traces");
/// Every case steps at 1 ms, the firmware's `DT_US` and the crate's own
/// tests' step.
const DT_US: u32 = 1_000;

/// What the file is compared against: itself across commits, or an
/// oracle too.
#[derive(Clone, Copy)]
pub enum Kind {
    Regression,
    Reference,
}

/// Which steps get a row.
#[derive(Clone, Copy)]
pub enum Rows {
    All,
    Spikes,
}

/// One case: a name, what it is, how long it runs, and how to build it.
pub struct Case {
    pub name: &'static str,
    pub kind: Kind,
    pub steps: u32,
    pub rows: Rows,
    pub build: fn() -> Run,
}

/// A built network and its drive: the input currents (μA per neuron) of a
/// given step.
pub struct Run {
    pub net: SpikingNeuralNetwork,
    pub drive: Box<dyn Fn(u32) -> Vec<i16>>,
}

/// The file of a case.
pub fn path(case: &Case) -> PathBuf {
    Path::new(DIR).join(format!("{}.trace", case.name))
}

/// Build the case, run it, and return the file's text.
///
/// # Panics
///
/// When a step fails, which the public API only does for a bad
/// construction, and every case here constructs.
pub fn render(case: &Case) -> String {
    let Run { mut net, drive } = (case.build)();
    let res = match net.neurons()[0].voltage_resolution {
        VoltageResolution::Millivolt => "mV",
        VoltageResolution::CentiMillivolt => "cmV",
    };
    let mut out = format!(
        "# {FORMAT} case={} kind={} n={} dt_us={DT_US} res={res} plasticity={} divisor={} steps={} rows={}\n",
        case.name,
        match case.kind {
            Kind::Regression => "regression",
            Kind::Reference => "reference",
        },
        net.neuron_count(),
        if net.plasticity_enabled() { "on" } else { "off" },
        net.synaptic_input_divisor(),
        case.steps,
        match case.rows {
            Rows::All => "all",
            Rows::Spikes => "spikes",
        },
    );
    for step in 0..case.steps {
        let time_us = net.current_time_us();
        let spikes = net.step(&drive(step)).expect("a built case steps");
        if matches!(case.rows, Rows::Spikes) && spikes.is_empty() {
            continue;
        }
        let ids: Vec<String> = spikes.iter().map(|s| s.neuron_id.to_string()).collect();
        let membranes: Vec<String> = net
            .neurons()
            .iter()
            .map(|n| n.membrane_potential.to_string())
            .collect();
        out.push_str(&format!(
            "{step} {time_us} | {} | {}\n",
            ids.join(" "),
            membranes.join(" ")
        ));
    }
    out
}

/// A neuron with the noise set; the network's constructors keep the
/// default (5 μA), and a case that wants silence builds its neurons here
/// and hands them to `from_neurons`.
fn neuron(id: u16, kind: NeuronType, res: VoltageResolution, noise_ua: u8) -> LIFNeuron {
    let mut n = LIFNeuron::new_with_type_resolution(id, kind, res);
    n.noise_amplitude_ua = noise_ua;
    n
}

/// A network from given neurons, with the given edges, finalized.
fn wired(neurons: Vec<LIFNeuron>, edges: &[(u16, u16, i16)]) -> SpikingNeuralNetwork {
    let mut net = SpikingNeuralNetwork::from_neurons(neurons, DT_US).expect("neurons given");
    for &(pre, post, w) in edges {
        net.add_synapse(pre, post, w)
            .expect("ids in range, no self edge");
    }
    if !edges.is_empty() {
        net.finalize_synapses();
    }
    net
}

/// Every case, in file order.
pub const CASES: &[Case] = &[
    Case {
        name: "neuron-reference",
        kind: Kind::Reference,
        steps: 150,
        rows: Rows::All,
        build: neuron_reference,
    },
    Case {
        name: "one-neuron-board",
        kind: Kind::Regression,
        steps: 10_000,
        rows: Rows::Spikes,
        build: one_neuron_board,
    },
];

/// The reference vector: one excitatory neuron on the centi-mV grid, no
/// noise, the threshold out of reach (so the vector is the integration
/// alone, and the oracle needs no spike, reset, refractory or adaptation
/// term). The drive walks four regimes: the board's 160 μA toward its
/// steady state, the largest current to the ceiling, the smallest to the
/// floor, then nothing, back toward rest.
fn neuron_reference() -> Run {
    let mut n = neuron(
        0,
        NeuronType::Excitatory,
        VoltageResolution::CentiMillivolt,
        0,
    );
    n.threshold = i16::MAX;
    let mut net = wired(vec![n], &[]);
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|step| {
            vec![match step {
                0..=39 => 160,
                40..=69 => i16::MAX,
                70..=99 => i16::MIN,
                _ => 0,
            }]
        }),
    }
}

/// The firmware's neuron (`firmware/esp32c3/src/main.rs`): excitatory,
/// centi-mV grid, the constructor's noise, 160 μA, one step per ms for
/// 10,000 steps. The network's step does what the firmware's `step` does
/// (adaptation decay, then integrate at `step × DT_US`), so the spike
/// rows fold to the board's record: 147 spikes, the first at step 55,
/// checksum `0b78b456` (`evidence/esp32c3-bringup/README.md`).
fn one_neuron_board() -> Run {
    let mut net = wired(
        vec![LIFNeuron::new_with_type_resolution(
            0,
            NeuronType::Excitatory,
            VoltageResolution::CentiMillivolt,
        )],
        &[],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|_| vec![160]),
    }
}
