//! The trace cases and their writer, shared by `examples/trace.rs` (which
//! writes the files) and `tests/traces.rs` (which compares them). No
//! library code: a case is a network built through the public API plus a
//! drive, and a row is what `step()` returned and `neurons()` after it.
//!
//! Format `neuralos-trace v1`, one file per case in this directory:
//!
//! ```text
//! # neuralos-trace v1 case=<name> kind=<regression|reference> n=<neurons> dt_us=<dt> res=<mV|cmV> plasticity=<on|off> divisor=<d> steps=<N> rows=<all|spikes>
//! <step> <time_us> | <spiking neuron ids> | <membrane of every neuron, i16 quanta>
//! ```
//!
//! One row per step (`rows=all`), or one per step that spiked
//! (`rows=spikes`; the board case is 10,000 steps and 147 rows). A row is
//! written after its step: `time_us` is the step's own timestamp, the one
//! its spikes carry; the ids are the spikes `step()` returned, in neuron
//! order, nothing between the bars when the step was silent; the
//! membranes are `neurons()` after the step, so a neuron that fired shows
//! its reset potential. Everything is decimal. Where a case keeps the
//! noise, it is the neuron's own LFSR, seeded by id and time, so every
//! case is a pure function of this file.
//!
//! Two words, two meanings (PR B). A `regression` trace comes from this
//! code and is compared with itself across commits: a trace that moves is
//! red, and a deliberate move is regenerated by
//! `cargo run -p neuralos-snn --example trace -- write` in a commit whose
//! message says which cases moved and why. A `reference` vector is also
//! checked against an oracle that is not this code: the unbounded-integer
//! neuron equation in `tests/traces.rs`. The only oracle today is that
//! neuron model, so there is one reference vector, a bare neuron with no
//! synapse and no spike.
//!
//! The fixed network. `freeze` writes `frozen.rs` in this directory: every
//! case whose network has plasticity off, as the arrays a `FixedNetwork`
//! steps, and `for_each_frozen!` over them. `plasticity-on` is the one
//! case it cannot freeze, since a `FixedNetwork` has no plasticity. A
//! frozen network writes its rows through `row.rs`, a second writer
//! beside `render`, and `tests/traces.rs` holds both against the files.

use std::path::{Path, PathBuf};

use neuralos_snn::nir::{NirImport, NirImportOptions};
use neuralos_snn::{
    FixedSynapse, LIFNeuron, NetworkTopology, NeuronType, SpikingNeuralNetwork, VoltageResolution,
};

/// The format line's name and version.
pub const FORMAT: &str = "neuralos-trace v1";
/// Where the files live: this directory, resolved from the crate root.
pub const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/traces");
/// Every case steps at 1 ms, the firmware's `DT_US` and the crate's own
/// tests' step.
const DT_US: u32 = 1_000;

/// What the file is compared against: itself across commits, or an
/// oracle too.
#[derive(Clone, Copy)]
pub enum Kind {
    Regression,
    Reference,
}

/// Which steps get a row.
#[derive(Clone, Copy)]
pub enum Rows {
    All,
    Spikes,
}

/// One case: a name, what it is, how long it runs, and how to build it.
pub struct Case {
    pub name: &'static str,
    pub kind: Kind,
    pub steps: u32,
    pub rows: Rows,
    pub build: fn() -> Run,
}

/// A built network and its drive: the input currents (μA per neuron) of a
/// given step.
pub struct Run {
    pub net: SpikingNeuralNetwork,
    pub drive: Box<dyn Fn(u32) -> Vec<i16>>,
}

/// The file of a case.
pub fn path(case: &Case) -> PathBuf {
    Path::new(DIR).join(format!("{}.trace", case.name))
}

/// A case's header line, the file's first, without its newline: what the
/// built network says of itself before its first step.
fn header(case: &Case, net: &SpikingNeuralNetwork) -> String {
    let res = match net.neurons()[0].voltage_resolution {
        VoltageResolution::Millivolt => "mV",
        VoltageResolution::CentiMillivolt => "cmV",
    };
    format!(
        "# {FORMAT} case={} kind={} n={} dt_us={DT_US} res={res} plasticity={} divisor={} steps={} rows={}",
        case.name,
        match case.kind {
            Kind::Regression => "regression",
            Kind::Reference => "reference",
        },
        net.neuron_count(),
        if net.plasticity_enabled() { "on" } else { "off" },
        net.synaptic_input_divisor(),
        case.steps,
        match case.rows {
            Rows::All => "all",
            Rows::Spikes => "spikes",
        },
    )
}

/// The frozen file, `frozen.rs` in this directory.
pub fn frozen_path() -> PathBuf {
    Path::new(DIR).join("frozen.rs")
}

/// The head of `frozen.rs`: what it is, how it is made and kept, and its
/// one allow.
const FROZEN_PREAMBLE: &str = "\
// Generated by `cargo run -p neuralos-snn --example trace -- write` from
// tests/traces/cases.rs (`cases::freeze`); do not edit it by hand.
// tests/traces.rs regenerates it and compares line for line.
//
// Every plasticity-off case of tests/traces/ as the arrays a FixedNetwork
// steps: N neurons and S synapses, the time step, the run, whether the
// trace keeps spiking steps only, the trace's header line verbatim, the
// neurons as built (every field), the synapses in the CSR order, and the
// drive as runs of equal steps, (count, currents). plasticity-on is not
// here: a FixedNetwork has no plasticity.
//
// Included by #[path] with #[rustfmt::skip] on the `mod frozen;` line, so
// rustfmt leaves it as written: by tests/traces.rs, and by firmware, since
// it needs only core and neuralos-snn. One allow, builtin: dead_code, since
// an includer reads only the constants it needs.
#![allow(dead_code)]
";

/// The text of `frozen.rs` (module doc): every plasticity-off case, built,
/// as one module named after it (`-` becomes `_`) holding `N`, `S`,
/// `DT_US`, `STEPS`, `SPIKES_ONLY`, `HEADER` (the trace's first line,
/// verbatim), `NEURONS` (every field, as built, before the first step),
/// `SYNAPSES` (`FixedSynapse::from_network`: the CSR order) and `DRIVE`
/// (runs of equal steps). Then `for_each_frozen!`, which applies a
/// caller's macro to every module, so no list is kept by hand.
///
/// # Panics
///
/// When a case's drive is not one current per neuron, which no case here
/// is.
pub fn freeze() -> String {
    let mut out = String::from(FROZEN_PREAMBLE);
    let mut modules = Vec::new();
    for case in CASES {
        let Run { net, drive } = (case.build)();
        if net.plasticity_enabled() {
            continue;
        }
        let module = case.name.replace('-', "_");
        let n = net.neurons().len();
        let synapses = FixedSynapse::from_network(&net);
        out.push_str(&format!("\npub mod {module} {{\n"));
        out.push_str(
            "    use neuralos_snn::{FixedSynapse, LIFNeuron, NeuronType, VoltageResolution};\n\n",
        );
        out.push_str(&format!("    pub const N: usize = {n};\n"));
        out.push_str(&format!("    pub const S: usize = {};\n", synapses.len()));
        out.push_str(&format!("    pub const DT_US: u32 = {DT_US};\n"));
        out.push_str(&format!("    pub const STEPS: u32 = {};\n", case.steps));
        out.push_str(&format!(
            "    pub const SPIKES_ONLY: bool = {};\n",
            matches!(case.rows, Rows::Spikes)
        ));
        out.push_str(&format!(
            "    pub const HEADER: &str = {:?};\n",
            header(case, &net)
        ));
        out.push_str("    pub const NEURONS: [LIFNeuron; N] = [\n");
        for neuron in net.neurons() {
            out.push_str(&format!("        {},\n", neuron_literal(neuron)));
        }
        out.push_str("    ];\n");
        if synapses.is_empty() {
            out.push_str("    pub const SYNAPSES: [FixedSynapse; S] = [];\n");
        } else {
            out.push_str("    pub const SYNAPSES: [FixedSynapse; S] = [\n");
            for s in &synapses {
                out.push_str(&format!(
                    "        FixedSynapse {{ pre: {}, post: {}, pulse_ua: {} }},\n",
                    s.pre, s.post, s.pulse_ua
                ));
            }
            out.push_str("    ];\n");
        }
        out.push_str("    pub const DRIVE: &[(u32, [i16; N])] = &[\n");
        for (count, currents) in runs(case.name, &*drive, case.steps, n) {
            let currents: Vec<String> = currents.iter().map(i16::to_string).collect();
            out.push_str(&format!("        ({count}, [{}]),\n", currents.join(", ")));
        }
        out.push_str("    ];\n}\n");
        modules.push(module);
    }
    out.push_str(
        "\n/// Applies the caller's macro to every frozen case, in file order.\n\
         macro_rules! for_each_frozen {\n    ($m:ident) => {\n",
    );
    for module in &modules {
        out.push_str(&format!("        $m!({module});\n"));
    }
    out.push_str("    };\n}\npub(crate) use for_each_frozen;\n");
    out
}

/// A neuron as a struct literal, every field by name. The pattern lists
/// every field too, so a field added to `LIFNeuron` fails to compile here
/// until the freezer writes it.
fn neuron_literal(n: &LIFNeuron) -> String {
    let LIFNeuron {
        id,
        neuron_type,
        membrane_potential,
        resting_potential,
        threshold,
        reset_potential,
        voltage_resolution,
        tau_membrane_us,
        tau_refractory_us,
        refractory_time_us,
        last_update_time_us,
        last_spike_time_us,
        synaptic_current_ua,
        capacitance_pf,
        resistance_mohm,
        noise_amplitude_ua,
        adaptation_current_ua,
    } = n;
    format!(
        "LIFNeuron {{ id: {id}, neuron_type: NeuronType::{neuron_type:?}, \
         membrane_potential: {membrane_potential}, resting_potential: {resting_potential}, \
         threshold: {threshold}, reset_potential: {reset_potential}, \
         voltage_resolution: VoltageResolution::{voltage_resolution:?}, \
         tau_membrane_us: {tau_membrane_us}, tau_refractory_us: {tau_refractory_us}, \
         refractory_time_us: {refractory_time_us}, last_update_time_us: {last_update_time_us}, \
         last_spike_time_us: {last_spike_time_us}, synaptic_current_ua: {synaptic_current_ua}, \
         capacitance_pf: {capacitance_pf}, resistance_mohm: {resistance_mohm}, \
         noise_amplitude_ua: {noise_amplitude_ua}, adaptation_current_ua: {adaptation_current_ua} }}"
    )
}

/// A case's drive over its run, as runs of equal steps: `(count,
/// currents)`, one current per neuron.
fn runs(name: &str, drive: &dyn Fn(u32) -> Vec<i16>, steps: u32, n: usize) -> Vec<(u32, Vec<i16>)> {
    let mut runs: Vec<(u32, Vec<i16>)> = Vec::new();
    for step in 0..steps {
        let currents = drive(step);
        assert_eq!(
            currents.len(),
            n,
            "{name} step {step}: one current per neuron"
        );
        match runs.last_mut() {
            Some((count, last)) if *last == currents => *count += 1,
            _ => runs.push((1, currents)),
        }
    }
    runs
}

/// Build the case, run it, and return the file's text.
///
/// # Panics
///
/// When a step fails, which the public API only does for a bad
/// construction, and every case here constructs.
pub fn render(case: &Case) -> String {
    let Run { mut net, drive } = (case.build)();
    let mut out = header(case, &net);
    out.push('\n');
    for step in 0..case.steps {
        let time_us = net.current_time_us();
        let spikes = net.step(&drive(step)).expect("a built case steps");
        if matches!(case.rows, Rows::Spikes) && spikes.is_empty() {
            continue;
        }
        let ids: Vec<String> = spikes.iter().map(|s| s.neuron_id.to_string()).collect();
        let membranes: Vec<String> = net
            .neurons()
            .iter()
            .map(|n| n.membrane_potential.to_string())
            .collect();
        out.push_str(&format!(
            "{step} {time_us} | {} | {}\n",
            ids.join(" "),
            membranes.join(" ")
        ));
    }
    out
}

/// A neuron with the noise set; the network's constructors keep the
/// default (5 μA), and a case that wants silence builds its neurons here
/// and hands them to `from_neurons`.
fn neuron(id: u16, kind: NeuronType, res: VoltageResolution, noise_ua: u8) -> LIFNeuron {
    let mut n = LIFNeuron::new_with_type_resolution(id, kind, res);
    n.noise_amplitude_ua = noise_ua;
    n
}

/// A network from given neurons, with the given edges, finalized.
fn wired(neurons: Vec<LIFNeuron>, edges: &[(u16, u16, i16)]) -> SpikingNeuralNetwork {
    let mut net = SpikingNeuralNetwork::from_neurons(neurons, DT_US).expect("neurons given");
    for &(pre, post, w) in edges {
        net.add_synapse(pre, post, w)
            .expect("ids in range, no self edge");
    }
    if !edges.is_empty() {
        net.finalize_synapses();
    }
    net
}

/// The reference chain of the NIR fixtures (`tests/nir_fixtures/`,
/// the pinned reference's own emission).
const NIR_CHAIN: &[u8] = include_bytes!("../nir_fixtures/chain.json");

/// A regression case over every step.
const fn regression(name: &'static str, steps: u32, build: fn() -> Run) -> Case {
    Case {
        name,
        kind: Kind::Regression,
        steps,
        rows: Rows::All,
        build,
    }
}

/// Every case, in file order: the reference vector, the board, then the
/// regression traces.
pub const CASES: &[Case] = &[
    Case {
        name: "neuron-reference",
        kind: Kind::Reference,
        steps: 150,
        rows: Rows::All,
        build: neuron_reference,
    },
    Case {
        name: "one-neuron-board",
        kind: Kind::Regression,
        steps: 10_000,
        rows: Rows::Spikes,
        build: one_neuron_board,
    },
    regression("chain-3", 100, chain_3),
    regression("feedforward-8", 150, feedforward_8),
    regression("recurrent-transmission", 30, recurrent_transmission),
    regression("centi-mv-grid", 30, centi_mv_grid),
    regression("inhibitory", 100, inhibitory),
    regression("refractory", 40, refractory),
    regression("plasticity-on", 150, plasticity_on),
    regression("plasticity-off", 150, plasticity_off),
    regression("saturation-floor-ceiling", 100, saturation_floor_ceiling),
    regression("nir-chain-fixture", 100, nir_chain_fixture),
    regression("ternary-weights", 100, ternary_weights),
];

/// The reference vector: one excitatory neuron on the centi-mV grid, no
/// noise, the threshold out of reach (so the vector is the integration
/// alone, and the oracle needs no spike, reset, refractory or adaptation
/// term). The drive walks four regimes: the board's 160 μA toward its
/// steady state, the largest current to the ceiling, the smallest to the
/// floor, then nothing, back toward rest.
fn neuron_reference() -> Run {
    let mut n = neuron(
        0,
        NeuronType::Excitatory,
        VoltageResolution::CentiMillivolt,
        0,
    );
    n.threshold = i16::MAX;
    let mut net = wired(vec![n], &[]);
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|step| {
            vec![match step {
                0..=39 => 160,
                40..=69 => i16::MAX,
                70..=99 => i16::MIN,
                _ => 0,
            }]
        }),
    }
}

/// The firmware's neuron (`firmware/esp32c3/src/main.rs`): excitatory,
/// centi-mV grid, the constructor's noise, 160 μA, one step per ms for
/// 10,000 steps. The network's step does what the firmware's `step` does
/// (adaptation decay, then integrate at `step × DT_US`), so the spike
/// rows fold to the board's record: 147 spikes, the first at step 55,
/// checksum `0b78b456` (`evidence/esp32c3-bringup/README.md`).
fn one_neuron_board() -> Run {
    let mut net = wired(
        vec![LIFNeuron::new_with_type_resolution(
            0,
            NeuronType::Excitatory,
            VoltageResolution::CentiMillivolt,
        )],
        &[],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|_| vec![160]),
    }
}

/// Three excitatory neurons in a line, centi-mV, no noise, divisor 1 and
/// 5,000-weight edges: a 5,000 μA pulse lifts a neuron from anywhere
/// above its reset to threshold in one step. Neuron 0 is driven at
/// 600 μA and fires every ten steps or so; 1 fires the step after 0, and
/// 2 the step after 1.
fn chain_3() -> Run {
    let ns = (0..3)
        .map(|id| {
            neuron(
                id,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            )
        })
        .collect();
    let mut net = wired(ns, &[(0, 1, 5_000), (1, 2, 5_000)]);
    net.set_plasticity_enabled(false);
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 0, 0]),
    }
}

/// The `Feedforward` topology builder, layers 3-3-2, on the centi-mV
/// grid with the constructor's noise (the builder's neurons cannot be
/// reached before the first step; the LFSR is deterministic). Divisor 1,
/// so the builder's 100-weight edges land as 100 μA pulses, +50 quanta
/// on an excitatory neuron. The first layer is driven to fire every ten
/// steps or so; the second is biased at 148 μA, where the grid's
/// truncation parks it about 40 quanta under threshold and one pulse
/// fires it; the third, the two inhibitory neurons (ids 6 and 7, the
/// 80/20 split), at 199 μA, the same idea on its own threshold. A spiked
/// neuron takes most of a hundred steps to climb back, so the deeper
/// layers fire twice in the window and the first fourteen times.
fn feedforward_8() -> Run {
    let mut net = SpikingNeuralNetwork::new_with_voltage_resolution(
        8,
        DT_US,
        NetworkTopology::Feedforward { layers: &[3, 3, 2] },
        VoltageResolution::CentiMillivolt,
    )
    .expect("8 neurons, 1 ms");
    net.build_topology().expect("layers sum to 8");
    net.set_plasticity_enabled(false);
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 600, 600, 148, 148, 148, 199, 199]),
    }
}

/// Session F's pin on the mV grid (`network.rs`,
/// `transmission_is_live_one_step_delayed_mv_strong_weight`): an
/// excitatory neuron fires at step 0 on 3,000 μA, and its 2,000-weight
/// edge moves the inhibitory neuron by +2 mV exactly one step later,
/// not on the spike's own step. Silent after step 0. Plasticity off: the
/// pin is transmission, here and in `centi-mv-grid`.
fn recurrent_transmission() -> Run {
    let mut net = wired(
        vec![
            neuron(0, NeuronType::Excitatory, VoltageResolution::Millivolt, 0),
            neuron(1, NeuronType::Inhibitory, VoltageResolution::Millivolt, 0),
        ],
        &[(0, 1, 2_000)],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|step| {
            if step == 0 {
                vec![3_000, 0]
            } else {
                vec![0, 0]
            }
        }),
    }
}

/// The same pin on the centi-mV grid
/// (`transmission_is_live_one_step_delayed_centimv`): a 125-weight edge,
/// a +12 μA pulse, and the inhibitory neuron moves −7,000 → −6,988, sub-mV
/// motion the mV grid cannot show.
fn centi_mv_grid() -> Run {
    let mut net = wired(
        vec![
            neuron(
                0,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
            neuron(
                1,
                NeuronType::Inhibitory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
        ],
        &[(0, 1, 125)],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|step| {
            if step == 0 {
                vec![3_000, 0]
            } else {
                vec![0, 0]
            }
        }),
    }
}

/// An inhibitory neuron (0) with a −10,000-weight edge onto an excitatory
/// one (1), both driven at 250 μA, centi-mV, no noise, divisor 10. Alone,
/// neuron 1 would fire every twelve steps or so; each −1,000 μA pulse
/// knocks it down by about 500 quanta, and it fires three times in the
/// window against neuron 0's five.
fn inhibitory() -> Run {
    let mut net = wired(
        vec![
            neuron(
                0,
                NeuronType::Inhibitory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
            neuron(
                1,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
        ],
        &[(0, 1, -10_000)],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|_| vec![250, 250]),
    }
}

/// One excitatory neuron at 3,000 μA, centi-mV, no noise: a spike, two
/// steps frozen at the reset potential (2 ms refractory at 1 ms steps),
/// two steps of climb, a spike. The adaptation current (+2 μA per spike,
/// −1 per step) is the slow drift in the climb.
fn refractory() -> Run {
    let mut net = wired(
        vec![neuron(
            0,
            NeuronType::Excitatory,
            VoltageResolution::CentiMillivolt,
            0,
        )],
        &[],
    );
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|_| vec![3_000]),
    }
}

/// Two excitatory neurons, centi-mV, no noise, one 1,000-weight edge at
/// divisor 1 (a +500-quanta pulse), 0 driven at 600 μA and 1 at 200 μA so
/// both fire and pair. With STDP on the weight drifts by a few units per
/// pairing, and each unit is visible in neuron 1's membrane on the pulse
/// steps; with it off the two traces part at the first pairing.
fn plastic(enabled: bool) -> Run {
    let ns = (0..2)
        .map(|id| {
            neuron(
                id,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            )
        })
        .collect();
    let mut net = wired(ns, &[(0, 1, 1_000)]);
    net.set_plasticity_enabled(enabled);
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 200]),
    }
}

fn plasticity_on() -> Run {
    plastic(true)
}

fn plasticity_off() -> Run {
    plastic(false)
}

/// One excitatory neuron on the mV grid, no noise, threshold out of
/// reach: the largest current pins the membrane at the +50 mV ceiling,
/// nothing lets it fall back (6 mV a step at first, then the mV grid's
/// truncation slows it), the smallest pins it at the −100 mV floor, and
/// nothing again.
fn saturation_floor_ceiling() -> Run {
    let mut n = neuron(0, NeuronType::Excitatory, VoltageResolution::Millivolt, 0);
    n.threshold = i16::MAX;
    let mut net = wired(vec![n], &[]);
    net.set_plasticity_enabled(false);
    Run {
        net,
        drive: Box::new(|step| {
            vec![match step {
                0..=19 => i16::MAX,
                20..=49 => 0,
                50..=69 => i16::MIN,
                _ => 0,
            }]
        }),
    }
}

/// The reference chain (Input 3 → Linear 1×3 → LIF → Output) imported
/// with the default options and built by `build_network`, driven through
/// its encoder with `[4, 0, 0]` as the assembly gate's frozen pin is:
/// 9 spikes in 100 steps, the first at step 6
/// (`examples/nir_assembly_gate.rs`, gate 6).
fn nir_chain_fixture() -> Run {
    let g = NirImport::from_json(NIR_CHAIN, NirImportOptions::default())
        .expect("the reference emission imports");
    let (net, enc, _report) = g.build_network().expect("the chain assembles");
    Run {
        net,
        drive: Box::new(move |_| enc.encode(&[&[4, 0, 0]])),
    }
}

/// Three excitatory neurons on the mV grid, no noise, edges 2,400, 900
/// and −1,500 snapped by `ternarize_weights` to ±γ with γ = 1,600 (the
/// mean magnitude), divisor 1: neuron 1 takes +8 mV per spike of 0,
/// neuron 2 takes +8 from 0 and −8 from 1. Neurons 1 and 2 are biased at
/// 300 μA so they fire on their own and the pulses move their timing.
fn ternary_weights() -> Run {
    let ns = (0..3)
        .map(|id| neuron(id, NeuronType::Excitatory, VoltageResolution::Millivolt, 0))
        .collect();
    let mut net = wired(ns, &[(0, 1, 2_400), (0, 2, 900), (1, 2, -1_500)]);
    let gamma = net.ternarize_weights();
    assert_eq!(gamma, 1_600, "the mean magnitude of 2,400, 900 and 1,500");
    net.set_plasticity_enabled(false);
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 300, 300]),
    }
}
