//! The trace cases and their writer, shared by `examples/trace.rs` (which
//! writes the files) and `tests/traces.rs` (which compares them). No
//! library code: a case is a network built through the public API plus a
//! drive, and a row is what `step()` returned and `neurons()` after it.
//!
//! Format `neuralos-trace v1`, one file per case in this directory:
//!
//! ```text
//! # neuralos-trace v1 case=<name> kind=<regression|reference> n=<neurons> dt_us=<dt> res=<mV|cmV> plasticity=<on|off> divisor=<d> steps=<N> rows=<all|spikes>
//! <step> <time_us> | <spiking neuron ids> | <membrane of every neuron, i16 quanta>
//! ```
//!
//! One row per step (`rows=all`), or one per step that spiked
//! (`rows=spikes`; the board case is 10,000 steps and 147 rows). A row is
//! written after its step: `time_us` is the step's own timestamp, the one
//! its spikes carry; the ids are the spikes `step()` returned, in neuron
//! order, nothing between the bars when the step was silent; the
//! membranes are `neurons()` after the step, so a neuron that fired shows
//! its reset potential. Everything is decimal. Where a case keeps the
//! noise, it is the neuron's own LFSR, seeded by id and time, so every
//! case is a pure function of this file.
//!
//! Two words, two meanings (PR B). A `regression` trace comes from this
//! code and is compared with itself across commits: a trace that moves is
//! red, and a deliberate move is regenerated by
//! `cargo run -p neuralos-snn --features unstable-stdp --example trace -- write`
//! in a commit whose
//! message says which cases moved and why. A `reference` vector is also
//! checked against an oracle that is not this code: the unbounded-integer
//! neuron equation in `tests/traces.rs`. The only oracle today is that
//! neuron model, so there is one reference vector, a bare neuron with no
//! synapse and no spike.
//!
//! The fixed network. `freeze` writes `frozen.rs` in this directory with
//! the library's freezer (`neuralos_snn::fixed::freeze`): every case
//! whose network has plasticity off, as the arrays a `FixedNetwork`
//! steps, and `for_each_frozen!` over them. `plasticity-on` is the one
//! case it cannot freeze, since a `FixedNetwork` has no plasticity. A
//! frozen network writes its rows through the library's row writer
//! (`neuralos_snn::fixed::row`), a second writer beside `render`, and
//! `tests/traces.rs` holds both against the files.

use std::path::{Path, PathBuf};

use neuralos_snn::fixed::freeze;
use neuralos_snn::nir::{NirImport, NirImportOptions};
use neuralos_snn::{
    FixedSynapse, LIFNeuron, NetworkTopology, NeuronType, SpikingNeuralNetwork, VoltageResolution,
};

/// The format line's name and version.
pub const FORMAT: &str = "neuralos-trace v1";
/// Where the files live: this directory, resolved from the crate root.
pub const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/traces");
/// Every case steps at 1 ms, the firmware's `DT_US` and the crate's own
/// tests' step.
const DT_US: u32 = 1_000;

/// What the file is compared against: itself across commits, or an
/// oracle too.
#[derive(Clone, Copy)]
pub enum Kind {
    Regression,
    Reference,
}

/// Which steps get a row.
#[derive(Clone, Copy)]
pub enum Rows {
    All,
    Spikes,
}

/// One case: a name, what it is, how long it runs, and how to build it.
pub struct Case {
    pub name: &'static str,
    pub kind: Kind,
    pub steps: u32,
    pub rows: Rows,
    pub build: fn() -> Run,
}

/// A built network and its drive: the input currents (μA per neuron) of a
/// given step.
pub struct Run {
    pub net: SpikingNeuralNetwork,
    pub drive: Box<dyn Fn(u32) -> Vec<i16>>,
}

/// The file of a case.
pub fn path(case: &Case) -> PathBuf {
    Path::new(DIR).join(format!("{}.trace", case.name))
}

/// A case's header line, the file's first, without its newline: what the
/// built network says of itself before its first step.
fn header(case: &Case, net: &SpikingNeuralNetwork) -> String {
    let res = match net.neurons()[0].voltage_resolution {
        VoltageResolution::Millivolt => "mV",
        VoltageResolution::CentiMillivolt => "cmV",
    };
    format!(
        "# {FORMAT} case={} kind={} n={} dt_us={DT_US} res={res} plasticity={} divisor={} steps={} rows={}",
        case.name,
        match case.kind {
            Kind::Regression => "regression",
            Kind::Reference => "reference",
        },
        net.neuron_count(),
        if net.plasticity_enabled() { "on" } else { "off" },
        net.synaptic_input_divisor(),
        case.steps,
        match case.rows {
            Rows::All => "all",
            Rows::Spikes => "spikes",
        },
    )
}

/// The frozen file, `frozen.rs` in this directory.
pub fn frozen_path() -> PathBuf {
    Path::new(DIR).join("frozen.rs")
}

/// The text of `frozen.rs` (module doc): every plasticity-off case, built,
/// as one module named after it (`-` becomes `_`) holding `N`, `S`,
/// `DT_US`, `STEPS`, `SPIKES_ONLY`, `HEADER` (the trace's first line,
/// verbatim), `NEURONS` (one constructor call and one setter per
/// parameter each, as built, before the first step), `SYNAPSES`
/// (`FixedSynapse::from_network`: the CSR order) and `DRIVE` (runs of
/// equal steps). Then `for_each_frozen!`, which applies a caller's macro
/// to every module, so no list is kept by hand.
///
/// # Panics
///
/// When a case's drive is not one current per neuron, which no case here
/// is; and with every refusal of `freeze::module` — a neuron that is not
/// at rest, an `id` that is not the neuron's position, a chain that does
/// not rebuild its neuron — none of which a case here trips: each is
/// built and frozen before its first step, and each numbers its neurons
/// from 0.
pub fn freeze() -> String {
    let mut out = String::from(freeze::preamble());
    let mut modules = Vec::new();
    for case in CASES {
        let Run { net, drive } = (case.build)();
        if net.plasticity_enabled() {
            continue;
        }
        let name = case.name.replace('-', "_");
        let drive = runs(case.name, &*drive, case.steps, net.neurons().len());
        out.push('\n');
        out.push_str(&freeze::module(
            &name,
            net.neurons(),
            &FixedSynapse::from_network(&net),
            DT_US,
            &header(case, &net),
            case.steps,
            matches!(case.rows, Rows::Spikes),
            &drive,
        ));
        modules.push(name);
    }
    out.push('\n');
    out.push_str(&freeze::tail(&modules));
    out
}

/// A case's drive over its run, as runs of equal steps: `(count,
/// currents)`, one current per neuron.
fn runs(name: &str, drive: &dyn Fn(u32) -> Vec<i16>, steps: u32, n: usize) -> Vec<(u32, Vec<i16>)> {
    let mut runs: Vec<(u32, Vec<i16>)> = Vec::new();
    for step in 0..steps {
        let currents = drive(step);
        assert_eq!(
            currents.len(),
            n,
            "{name} step {step}: one current per neuron"
        );
        match runs.last_mut() {
            Some((count, last)) if *last == currents => *count += 1,
            _ => runs.push((1, currents)),
        }
    }
    runs
}

/// Build the case, run it, and return the file's text.
///
/// # Panics
///
/// When a step fails, which the public API only does for a bad
/// construction, and every case here constructs.
pub fn render(case: &Case) -> String {
    let Run { mut net, drive } = (case.build)();
    let mut out = header(case, &net);
    out.push('\n');
    for step in 0..case.steps {
        let time_us = net.current_time_us();
        let spikes = net.step(&drive(step)).expect("a built case steps");
        if matches!(case.rows, Rows::Spikes) && spikes.is_empty() {
            continue;
        }
        let ids: Vec<String> = spikes.iter().map(|s| s.neuron_id.to_string()).collect();
        let membranes: Vec<String> = net
            .neurons()
            .iter()
            .map(|n| n.membrane_potential.to_string())
            .collect();
        out.push_str(&format!(
            "{step} {time_us} | {} | {}\n",
            ids.join(" "),
            membranes.join(" ")
        ));
    }
    out
}

/// A neuron with the noise set; the network's constructors keep the
/// default (5 μA), and a case that wants silence builds its neurons here
/// and hands them to `from_neurons`.
fn neuron(id: u16, kind: NeuronType, res: VoltageResolution, noise_ua: u8) -> LIFNeuron {
    let mut n = LIFNeuron::new_with_type_resolution(id, kind, res);
    n.noise_amplitude_ua = noise_ua;
    n
}

/// A network from given neurons, with the given edges, finalized.
fn wired(neurons: Vec<LIFNeuron>, edges: &[(u16, u16, i16)]) -> SpikingNeuralNetwork {
    let mut net = SpikingNeuralNetwork::from_neurons(neurons, DT_US).expect("neurons given");
    for &(pre, post, w) in edges {
        net.add_synapse(pre, post, w)
            .expect("ids in range, no self edge");
    }
    if !edges.is_empty() {
        net.finalize_synapses();
    }
    net
}

/// The reference chain of the NIR fixtures (`tests/nir_fixtures/`,
/// the pinned reference's own emission).
const NIR_CHAIN: &[u8] = include_bytes!("../nir_fixtures/chain.json");
/// The two witnesses of D8, the spiking Linear edge, as
/// `neuralos-nir2json --sim-units` converts them
/// (`tests/nir_fixtures/README.md`).
const SNNTORCH_TWO_LAYER: &[u8] = include_bytes!("../nir_fixtures/snntorch_two_layer_sim.json");
const TWO_LIF_NEURONS: &[u8] = include_bytes!("../nir_fixtures/two_lif_neurons_sim.json");

/// A regression case over every step.
const fn regression(name: &'static str, steps: u32, build: fn() -> Run) -> Case {
    Case {
        name,
        kind: Kind::Regression,
        steps,
        rows: Rows::All,
        build,
    }
}

/// Every case, in file order: the reference vector, the board, then the
/// regression traces.
pub const CASES: &[Case] = &[
    Case {
        name: "neuron-reference",
        kind: Kind::Reference,
        steps: 150,
        rows: Rows::All,
        build: neuron_reference,
    },
    Case {
        name: "one-neuron-board",
        kind: Kind::Regression,
        steps: 10_000,
        rows: Rows::Spikes,
        build: one_neuron_board,
    },
    regression("chain-3", 100, chain_3),
    regression("feedforward-8", 150, feedforward_8),
    regression("recurrent-transmission", 30, recurrent_transmission),
    regression("centi-mv-grid", 30, centi_mv_grid),
    regression("inhibitory", 100, inhibitory),
    regression("refractory", 40, refractory),
    #[cfg(feature = "unstable-stdp")]
    regression("plasticity-on", 150, plasticity_on),
    regression("plasticity-off", 150, plasticity_off),
    regression("saturation-floor-ceiling", 100, saturation_floor_ceiling),
    regression("nir-chain-fixture", 100, nir_chain_fixture),
    regression("ternary-weights", 100, ternary_weights),
    regression("snntorch-two-layer", 150, snntorch_two_layer),
    regression("two-lif-neurons", 150, two_lif_neurons),
];

/// The reference vector: one excitatory neuron on the centi-mV grid, no
/// noise, the threshold out of reach (so the vector is the integration
/// alone, and the oracle needs no spike, reset, refractory or adaptation
/// term). The drive walks four regimes: the board's 160 μA toward its
/// steady state, the largest current to the ceiling, the smallest to the
/// floor, then nothing, back toward rest.
fn neuron_reference() -> Run {
    let mut n = neuron(
        0,
        NeuronType::Excitatory,
        VoltageResolution::CentiMillivolt,
        0,
    );
    n.threshold = i16::MAX;
    let net = wired(vec![n], &[]);
    Run {
        net,
        drive: Box::new(|step| {
            vec![match step {
                0..=39 => 160,
                40..=69 => i16::MAX,
                70..=99 => i16::MIN,
                _ => 0,
            }]
        }),
    }
}

/// The firmware's neuron (`firmware/esp32c3/src/main.rs`): excitatory,
/// centi-mV grid, the constructor's noise, 160 μA, one step per ms for
/// 10,000 steps. The network's step does what the firmware's `step` does
/// (adaptation decay, then integrate at `step × DT_US`), so the spike
/// rows fold to the board's record: 147 spikes, the first at step 55,
/// checksum `0b78b456` (`evidence/esp32c3-bringup/README.md`).
fn one_neuron_board() -> Run {
    let net = wired(
        vec![LIFNeuron::new_with_type_resolution(
            0,
            NeuronType::Excitatory,
            VoltageResolution::CentiMillivolt,
        )],
        &[],
    );
    Run {
        net,
        drive: Box::new(|_| vec![160]),
    }
}

/// Three excitatory neurons in a line, centi-mV, no noise, divisor 1 and
/// 5,000-weight edges: a 5,000 μA pulse lifts a neuron from anywhere
/// above its reset to threshold in one step. Neuron 0 is driven at
/// 600 μA and fires every ten steps or so; 1 fires the step after 0, and
/// 2 the step after 1.
fn chain_3() -> Run {
    let ns = (0..3)
        .map(|id| {
            neuron(
                id,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            )
        })
        .collect();
    let mut net = wired(ns, &[(0, 1, 5_000), (1, 2, 5_000)]);
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 0, 0]),
    }
}

/// The `Feedforward` topology builder, layers 3-3-2, on the centi-mV
/// grid with the constructor's noise (the builder's neurons cannot be
/// reached before the first step; the LFSR is deterministic). Divisor 1,
/// so the builder's 100-weight edges land as 100 μA pulses, +50 quanta
/// on an excitatory neuron. The first layer is driven to fire every ten
/// steps or so; the second is biased at 148 μA, where the grid's
/// truncation parks it about 40 quanta under threshold and one pulse
/// fires it; the third, the two inhibitory neurons (ids 6 and 7, the
/// 80/20 split), at 199 μA, the same idea on its own threshold. A spiked
/// neuron takes most of a hundred steps to climb back, so the deeper
/// layers fire twice in the window and the first fourteen times.
fn feedforward_8() -> Run {
    let mut net = SpikingNeuralNetwork::new_with_voltage_resolution(
        8,
        DT_US,
        NetworkTopology::Feedforward { layers: &[3, 3, 2] },
        VoltageResolution::CentiMillivolt,
    )
    .expect("8 neurons, 1 ms");
    net.build_topology().expect("layers sum to 8");
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 600, 600, 148, 148, 148, 199, 199]),
    }
}

/// Session F's pin on the mV grid (`network.rs`,
/// `transmission_is_live_one_step_delayed_mv_strong_weight`): an
/// excitatory neuron fires at step 0 on 3,000 μA, and its 2,000-weight
/// edge moves the inhibitory neuron by +2 mV exactly one step later,
/// not on the spike's own step. Silent after step 0. Plasticity off: the
/// pin is transmission, here and in `centi-mv-grid`.
fn recurrent_transmission() -> Run {
    let net = wired(
        vec![
            neuron(0, NeuronType::Excitatory, VoltageResolution::Millivolt, 0),
            neuron(1, NeuronType::Inhibitory, VoltageResolution::Millivolt, 0),
        ],
        &[(0, 1, 2_000)],
    );
    Run {
        net,
        drive: Box::new(|step| {
            if step == 0 {
                vec![3_000, 0]
            } else {
                vec![0, 0]
            }
        }),
    }
}

/// The same pin on the centi-mV grid
/// (`transmission_is_live_one_step_delayed_centimv`): a 125-weight edge,
/// a +12 μA pulse, and the inhibitory neuron moves −7,000 → −6,988, sub-mV
/// motion the mV grid cannot show.
fn centi_mv_grid() -> Run {
    let net = wired(
        vec![
            neuron(
                0,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
            neuron(
                1,
                NeuronType::Inhibitory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
        ],
        &[(0, 1, 125)],
    );
    Run {
        net,
        drive: Box::new(|step| {
            if step == 0 {
                vec![3_000, 0]
            } else {
                vec![0, 0]
            }
        }),
    }
}

/// An inhibitory neuron (0) with a −10,000-weight edge onto an excitatory
/// one (1), both driven at 250 μA, centi-mV, no noise, divisor 10. Alone,
/// neuron 1 would fire every twelve steps or so; each −1,000 μA pulse
/// knocks it down by about 500 quanta, and it fires three times in the
/// window against neuron 0's five.
fn inhibitory() -> Run {
    let net = wired(
        vec![
            neuron(
                0,
                NeuronType::Inhibitory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
            neuron(
                1,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            ),
        ],
        &[(0, 1, -10_000)],
    );
    Run {
        net,
        drive: Box::new(|_| vec![250, 250]),
    }
}

/// One excitatory neuron at 3,000 μA, centi-mV, no noise: a spike, two
/// steps frozen at the reset potential (2 ms refractory at 1 ms steps),
/// two steps of climb, a spike. The adaptation current (+2 μA per spike,
/// −1 per step) is the slow drift in the climb.
fn refractory() -> Run {
    let net = wired(
        vec![neuron(
            0,
            NeuronType::Excitatory,
            VoltageResolution::CentiMillivolt,
            0,
        )],
        &[],
    );
    Run {
        net,
        drive: Box::new(|_| vec![3_000]),
    }
}

/// Two excitatory neurons, centi-mV, no noise, one 1,000-weight edge at
/// divisor 1 (a +500-quanta pulse), 0 driven at 600 μA and 1 at 200 μA so
/// both fire and pair. With STDP on the weight drifts by a few units per
/// pairing, and each unit is visible in neuron 1's membrane on the pulse
/// steps; with it off the two traces part at the first pairing.
fn plastic(enabled: bool) -> Run {
    let ns = (0..2)
        .map(|id| {
            neuron(
                id,
                NeuronType::Excitatory,
                VoltageResolution::CentiMillivolt,
                0,
            )
        })
        .collect();
    let mut net = wired(ns, &[(0, 1, 1_000)]);
    #[cfg(feature = "unstable-stdp")]
    net.set_plasticity_enabled(enabled);
    #[cfg(not(feature = "unstable-stdp"))]
    assert!(!enabled, "no switch without `unstable-stdp`");
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 200]),
    }
}

#[cfg(feature = "unstable-stdp")]
fn plasticity_on() -> Run {
    plastic(true)
}

fn plasticity_off() -> Run {
    plastic(false)
}

/// One excitatory neuron on the mV grid, no noise, threshold out of
/// reach: the largest current pins the membrane at the +50 mV ceiling,
/// nothing lets it fall back (6 mV a step at first, then the mV grid's
/// truncation slows it), the smallest pins it at the −100 mV floor, and
/// nothing again.
fn saturation_floor_ceiling() -> Run {
    let mut n = neuron(0, NeuronType::Excitatory, VoltageResolution::Millivolt, 0);
    n.threshold = i16::MAX;
    let net = wired(vec![n], &[]);
    Run {
        net,
        drive: Box::new(|step| {
            vec![match step {
                0..=19 => i16::MAX,
                20..=49 => 0,
                50..=69 => i16::MIN,
                _ => 0,
            }]
        }),
    }
}

/// The reference chain (Input 3 → Linear 1×3 → LIF → Output) imported
/// with the default options and built by `build_network`, driven through
/// its encoder with `[4, 0, 0]` as the assembly gate's frozen pin is:
/// 9 spikes in 100 steps, the first at step 6
/// (`examples/nir_assembly_gate.rs`, gate 6).
fn nir_chain_fixture() -> Run {
    let g = NirImport::from_json(NIR_CHAIN, NirImportOptions::default())
        .expect("the reference emission imports");
    let (net, enc, _report) = g.build_network().expect("the chain assembles");
    Run {
        net,
        drive: Box::new(move |_| enc.encode(&[&[4, 0, 0]])),
    }
}

/// Three excitatory neurons on the mV grid, no noise, edges 2,400, 900
/// and −1,500 snapped by `ternarize_weights` to ±γ with γ = 1,600 (the
/// mean magnitude), divisor 1: neuron 1 takes +8 mV per spike of 0,
/// neuron 2 takes +8 from 0 and −8 from 1. Neurons 1 and 2 are biased at
/// 300 μA so they fire on their own and the pulses move their timing.
fn ternary_weights() -> Run {
    let ns = (0..3)
        .map(|id| neuron(id, NeuronType::Excitatory, VoltageResolution::Millivolt, 0))
        .collect();
    let mut net = wired(ns, &[(0, 1, 2_400), (0, 2, 900), (1, 2, -1_500)]);
    let gamma = net.ternarize_weights();
    assert_eq!(gamma, 1_600, "the mean magnitude of 2,400, 900 and 1,500");
    net.set_synaptic_input_divisor(1).expect("nonzero");
    Run {
        net,
        drive: Box::new(|_| vec![600, 300, 300]),
    }
}

/// A D8 witness imported on the centi-mV grid, which a spiking Linear
/// edge requires, and built by `build_network`: two neurons, lif1 → lif2
/// by one 327 μA synapse, driven through the graph's own encoder with
/// the one input feature `drive(step)`.
fn witness(json: &'static [u8], drive: fn(u32) -> i16) -> Run {
    let g = NirImport::from_json(
        json,
        NirImportOptions::new(DT_US, VoltageResolution::CentiMillivolt),
    )
    .expect("the converted witness imports");
    let (net, enc, _report) = g.build_network().expect("the two-layer graph assembles");
    Run {
        net,
        drive: Box::new(move |step| enc.encode(&[&[drive(step)]])),
    }
}

/// The framework witness: snnTorch 1.0's own export of `Linear → Leaky →
/// Linear → Leaky`. Input feature 1 on steps 0–9 and 50–59, else 0, so
/// the edge shows: lif1 fires on every other driven step (NIR's LIF has
/// no refractory; the assembly's minimum is one step), lif2 on the step
/// after each, on the pulse alone, and both are silent between the
/// bursts and after them.
fn snntorch_two_layer() -> Run {
    witness(SNNTORCH_TWO_LAYER, |step| {
        i16::from(matches!(step, 0..=9 | 50..=59))
    })
}

/// The reference witness: the NIR paper's own `two_lif_neurons`, the same
/// shape, input feature 1 every step. lif1's leak sits above its
/// threshold, so it would fire with no input; driven, it fires on every
/// other step, and lif2 on the step after each.
fn two_lif_neurons() -> Run {
    witness(TWO_LIF_NEURONS, |_| 1)
}
