//! NIR HDF5 gate (NIR slice 2) — THE EVIDENCE GATE of the HDF5
//! milestone, in the family style of `nir_format_gate`: the pinned
//! reference's OWN `write()` emissions, read end-to-end in pure Rust,
//! fired on the substrate, censused, exported, and read back.
//!
//! Fixtures: `tests/nir_fixtures/*.nir`, generated by
//! `tools/gen_nir_fixtures.py` (the pinned clone pip-installed into
//! `.nirenv`). The population chain reuses `chain_population.json`'s
//! exact values — the frozen quanta are cross-container comparable.
//!
//! Gates:
//! 1. the reference-written N>1 file reads end-to-end and quantizes
//!    to the EXACT frozen per-neuron quanta;
//! 2. the chain assembles onto a real `SpikingNeuralNetwork` and
//!    SPIKES under deterministic drive;
//! 3. the lzf fixture (reference-legal compression) rejects at the
//!    pre-read filter census, filter named, policy stated;
//! 4. our HDF5 export reads back SEMANTICALLY identical (named
//!    decision: HDF5 idempotence is record equality, not bytes);
//! 5. the JSON export from the same import stays byte-stable and
//!    re-imports state-identically (that contract is untouched).
//!
//! Exits non-zero on any gate failure. `NEURALOS_NIR_HDF5_OUT=<path>`
//! dumps the HDF5 export (e.g. for the reference-side `--verify`).

use std::path::PathBuf;

use neuralos_rt::nir_hdf5::{nir_hdf5_read, nir_hdf5_write, NirHdfError};
use neuralos_snn::nir::{NirImport, NirImportOptions};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/nir_fixtures")
        .join(name)
}

fn fail(msg: &str) -> ! {
    eprintln!("NIR HDF5 GATE: FAIL — {msg}");
    std::process::exit(1);
}

/// The frozen population quanta — identical to the JSON fixture pins.
const EXPECTED_LIFS: [(u32, i16, i16, i16, u16, u16); 2] = [
    (20_000, -70, -55, -80, 100, 200),
    (30_000, -65, -50, -75, 200, 150),
];
const EXPECTED_WEIGHTS: [i16; 6] = [16384, -32767, 8192, -8192, 32767, 16384];

fn main() {
    println!("=== NIR HDF5 gate — the reference's own .nir emissions ===");
    println!("ref     : neuromorphs/NIR @ {}", neuralos_snn::nir::NIR_REF_SHA);
    println!();

    // ---- gate 1: reference file reads + quantizes exactly ----------
    let doc = nir_hdf5_read(&fixture("chain_population.nir"))
        .unwrap_or_else(|e: NirHdfError| fail(&e.to_string()));
    println!(
        "fixture : chain_population.nir — {} nodes / {} edges / version \"{}\"",
        doc.nodes.len(),
        doc.edges.len(),
        doc.version
    );
    let opts = NirImportOptions::default();
    let g = doc.import(opts).unwrap_or_else(|e| fail(&e.to_string()));
    let lif_node = g.nodes.iter().find(|n| n.name == "lif").unwrap();
    let pop = lif_node.lif.unwrap();
    let lin = g.nodes.iter().find(|n| n.name == "linear").unwrap().linear.unwrap();
    for (i, (&r, (tau, leak, thr, reset, rr, c))) in g.lifs[pop.offset..pop.offset + pop.len]
        .iter()
        .zip(EXPECTED_LIFS)
        .enumerate()
    {
        println!(
            "quant   : LIF[{i}] tau {} us · R {} MOhm · leak {}/thr {}/reset {} quanta · C {} pF",
            r.tau_us, r.resistance_mohm, r.leak_q, r.threshold_q, r.reset_q, r.capacitance_pf
        );
        if (r.tau_us, r.leak_q, r.threshold_q, r.reset_q, r.resistance_mohm, r.capacitance_pf)
            != (tau, leak, thr, reset, rr, c)
        {
            fail("per-neuron quanta must be exactly the frozen values");
        }
    }
    let got: Vec<i16> = g.weights[lin.weight_offset..lin.weight_offset + 6].to_vec();
    println!("quant   : Linear {}x{} — weights {got:?}", lin.rows, lin.cols);
    if got != EXPECTED_WEIGHTS {
        fail("dyadic weights must quantize to the frozen vector");
    }
    println!("gate 1  : PASS — reference emission quantizes exactly (cross-container)");

    // ---- gate 2: assemble + fire ----------------------------------
    let (mut net, enc) = g
        .build_chain_network()
        .unwrap_or_else(|e| fail(&format!("assembly: {e}")));
    let mut spikes = 0usize;
    let mut first = usize::MAX;
    for t in 0..100u32 {
        let fired = net
            .step(&enc.encode(&[4, 0, 0]))
            .unwrap_or_else(|e| fail(&e.to_string()));
        if !fired.is_empty() && first == usize::MAX {
            first = t as usize;
        }
        spikes += fired.len();
    }
    if spikes == 0 {
        fail("the imported chain must spike under sustained drive");
    }
    println!("gate 2  : PASS — chain fires on the substrate: {spikes} spikes / 100 steps, first at step {first}");

    // ---- gate 3: named census rejection ---------------------------
    let err = nir_hdf5_read(&fixture("neg_filter_lzf.nir"))
        .expect_err("lzf must be censused out");
    let msg = err.to_string();
    if !msg.contains("lzf") || !msg.contains("deflate") {
        fail("the census rejection must name the filter and the policy");
    }
    println!("gate 3  : PASS — lzf censused out before any read, filter named, policy stated");

    // ---- gate 4: export → read-back semantic equality -------------
    let out = std::env::temp_dir().join("nir_hdf5_gate_export.nir");
    nir_hdf5_write(&out, &g).unwrap_or_else(|e| fail(&format!("export: {e}")));
    let doc2 = nir_hdf5_read(&out).unwrap_or_else(|e| fail(&format!("re-read: {e}")));
    let g2 = doc2.import(opts).unwrap_or_else(|e| fail(&format!("re-import: {e}")));
    if doc2.version != neuralos_snn::nir::EXPORT_VERSION {
        fail("our export must carry the provenance version block");
    }
    let semantically_equal = |a: &NirImport<'_>, b: &NirImport<'_>| -> bool {
        if a.nodes.len() != b.nodes.len() || a.edges.len() != b.edges.len() {
            return false;
        }
        for (na, nb) in a.nodes.iter().zip(&b.nodes) {
            if na.name != nb.name || na.kind != nb.kind || na.shape_len != nb.shape_len {
                return false;
            }
            if na.shape[..na.shape_len] != nb.shape[..nb.shape_len] {
                return false;
            }
            match (na.linear, nb.linear) {
                (Some(x), Some(y)) => {
                    if (x.rows, x.cols) != (y.rows, y.cols) {
                        return false;
                    }
                    if a.weights[x.weight_offset..x.weight_offset + x.rows * x.cols]
                        != b.weights[y.weight_offset..y.weight_offset + y.rows * y.cols]
                    {
                        return false;
                    }
                }
                (None, None) => {}
                _ => return false,
            }
            match (na.lif, nb.lif) {
                (Some(x), Some(y)) => {
                    if x.len != y.len
                        || a.lifs[x.offset..x.offset + x.len] != b.lifs[y.offset..y.offset + y.len]
                    {
                        return false;
                    }
                }
                (None, None) => {}
                _ => return false,
            }
        }
        true
    };
    if !semantically_equal(&g, &g2) {
        fail("read-back must be semantically identical (records, not bytes)");
    }
    println!(
        "gate 4  : PASS — HDF5 export read-back semantically identical (idempotence = record equality, the named decision)"
    );

    // ---- gate 5: JSON export byte-stability untouched -------------
    let mut ja = vec![0u8; 8192];
    let mut jb = vec![0u8; 8192];
    let na = neuralos_snn::nir::nir_export(&g.nodes, &g.edges, &g.weights, &g.lifs, g.opts, &mut ja)
        .unwrap_or_else(|e| fail(&format!("json export: {e}")));
    let nb = neuralos_snn::nir::nir_export(&g.nodes, &g.edges, &g.weights, &g.lifs, g.opts, &mut jb)
        .unwrap();
    if ja[..na] != jb[..nb] {
        fail("JSON export must stay byte-stable");
    }
    let gj = NirImport::from_json(&ja[..na], opts).unwrap_or_else(|e| fail(&format!("json re-import: {e}")));
    if !semantically_equal(&g, &gj) {
        fail("JSON re-import must be state-identical");
    }
    println!("gate 5  : PASS — JSON export byte-stable ({na} B) + state-identical re-import");
    println!();
    println!("NIR HDF5 GATE: PASS — 5/5 gates on reference-emitted .nir files");

    if let Ok(path) = std::env::var("NEURALOS_NIR_HDF5_OUT") {
        std::fs::copy(&out, &path)
            .unwrap_or_else(|e| fail(&format!("dump: {e}")));
        println!("dumped  : {path}");
    }
}
