//! NIR HDF5 assembly gate (R18 P4) — the cross-container leg of the
//! general-assembly slice, in the family style of `nir_hdf5_gate`:
//! the reference's own `.nir` emissions of the MERGE graph, read in
//! pure Rust, assembled with the general builder, and fired — with
//! record equality against the JSON container path.
//!
//! Fixtures: `tests/nir_fixtures/merge{,_uncompressed}.nir` (gzip
//! default + none), generated by `tools/gen_nir_fixtures.py` from
//! the same graph object as `neuralos-snn`'s `merge.json` — one
//! graph, three containers.
//!
//! Gates:
//! 1. the gzip pair reads and imports to IDENTICAL records
//!    (quantized weights + per-neuron LIF records bit-equal —
//!    compression is container-only);
//! 2. the HDF5 import and the JSON import produce the SAME records
//!    (the cross-container comparability contract);
//! 3. the merge graph ASSEMBLES from the HDF5 path and fires with
//!    the substrate's exact pins: a single branch stalls, the summed
//!    fan-in fires at step 52 (the snn-side gate's leg-2 mirror).
//!
//! Exits non-zero on any gate failure. Run with
//! `PATH="$PWD/.nirenv/bin:$PATH" cargo run -p neuralos-rt
//! --features hdf5 --example nir_hdf5_assembly_gate`.

use std::path::PathBuf;

use neuralos_rt::nir_hdf5::{nir_hdf5_read, NirHdfError};
use neuralos_snn::lif_neuron::VoltageResolution;
use neuralos_snn::nir::{NirImport, NirImportOptions};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/nir_fixtures")
        .join(name)
}

fn fail(msg: &str) -> ! {
    eprintln!("NIR HDF5 ASSEMBLY GATE: FAIL — {msg}");
    std::process::exit(1);
}

fn centi() -> NirImportOptions {
    NirImportOptions::new(1_000, VoltageResolution::CentiMillivolt)
}

fn main() {
    println!("=== NIR HDF5 assembly gate — the merge graph, three containers ===");
    println!("ref     : neuromorphs/NIR @ {}", neuralos_snn::nir::NIR_REF_SHA);
    println!();

    // ---- gate 1: gzip pair -> identical records --------------------
    let gz_doc = nir_hdf5_read(&fixture("merge.nir"))
        .unwrap_or_else(|e: NirHdfError| fail(&e.to_string()));
    let gz = gz_doc.import(centi()).unwrap_or_else(|e| fail(&e.to_string()));
    let raw_doc = nir_hdf5_read(&fixture("merge_uncompressed.nir"))
        .unwrap_or_else(|e: NirHdfError| fail(&e.to_string()));
    let raw = raw_doc.import(centi()).unwrap_or_else(|e| fail(&e.to_string()));
    println!("fixture : merge.nir (gzip) + merge_uncompressed.nir — {} nodes / {} edges",
        gz.nodes.len(), gz.edges.len());
    if gz.weights != raw.weights {
        fail("compression must be container-only: quantized weights differ");
    }
    if gz.lifs != raw.lifs {
        fail("compression must be container-only: LIF records differ");
    }
    println!("gate 1  : PASS — gzip and uncompressed import to identical records ({} weight cells)",
        gz.weights.len());

    // ---- gate 2: HDF5 == JSON (cross-container contract) -----------
    let json_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../neuralos-snn/tests/nir_fixtures/merge.json");
    let json_bytes = std::fs::read(&json_path)
        .unwrap_or_else(|e| fail(&format!("JSON fixture: {e} (regenerate via tools/gen_nir_fixtures.py)")));
    let js = NirImport::from_json(&json_bytes, centi())
        .unwrap_or_else(|e| fail(&format!("JSON import: {e}")));
    if gz.weights != js.weights {
        fail("HDF5 and JSON imports must quantize identically (weights)");
    }
    if gz.lifs != js.lifs {
        fail("HDF5 and JSON imports must quantize identically (LIF records)");
    }
    let names: Vec<&str> = gz.nodes.iter().map(|n| n.name).collect();
    if names != vec!["in1", "in2", "la", "lb", "lif", "out"] {
        fail(&format!("unexpected node order: {names:?}"));
    }
    println!("gate 2  : PASS — HDF5 and JSON paths produce the same records ({:?} node order)",
        names);

    // ---- gate 3: assemble + fire, the exact snn-side pins ----------
    let (mut net, enc, rep) = gz
        .build_network()
        .unwrap_or_else(|e| fail(&format!("assembly: {e}")));
    if (rep.neurons, rep.synapses, rep.drive_linears) != (2, 0, 2) {
        fail(&format!("unexpected report: {rep:?}"));
    }
    // single branch: neuron 0 stalls over 200 steps
    let mut n0 = 0usize;
    for _ in 0..200 {
        for s in net.step(&enc.encode(&[&[1, 1], &[]])).unwrap() {
            if s.neuron_id == 0 {
                n0 += 1;
            }
        }
    }
    if n0 != 0 {
        fail("single 81 uA branch must stall (neuron 0)");
    }
    // both branches: neuron 0 first spike at step 52 (the exact pin)
    let (mut net2, enc2, _) = gz.build_network().unwrap();
    let mut first = usize::MAX;
    for t in 0..100 {
        for s in net2.step(&enc2.encode(&[&[1, 1], &[1, 1]])).unwrap() {
            if s.neuron_id == 0 {
                first = first.min(t);
            }
        }
    }
    if first != 52 {
        fail(&format!("summed fan-in first spike must be step 52, got {first}"));
    }
    println!("gate 3  : PASS — assembles from the HDF5 path: single stalls (0/200), summed fires at step {first}");

    println!();
    println!("NIR HDF5 ASSEMBLY GATE: PASS — 3/3 gates, one graph across three containers");
}
