//! The freezer: a network as the Rust source of the arrays a
//! [`FixedNetwork`](super::FixedNetwork) steps. `std`: it writes
//! `String`s.
//!
//! A frozen file has three parts, one function each: the [`preamble`],
//! one [`module`] per network, and the [`tail`], the `for_each_frozen!`
//! macro over the modules. The library's trace tests write
//! `tests/traces/frozen.rs` with all three (`cases::freeze`), and
//! `neuralos-nir2json --freeze` writes one module for a stranger's graph.
//! A module needs only `core` and this crate, so firmware can include it.
//!
//! Provisional until the pub walk: alpha.9's later PRs may rename it.

// The text is built line by line, `format!` then `push_str`, as
// `cases::freeze` built it before the move: each line reads as the
// source it writes.
#![allow(clippy::format_push_string)]

use super::FixedSynapse;
use crate::lif_neuron::LIFNeuron;

/// The head of the library's frozen file (module doc).
const PREAMBLE: &str = "\
// Generated by `cargo run -p neuralos-snn --example trace -- write` from
// tests/traces/cases.rs (`cases::freeze`); do not edit it by hand.
// tests/traces.rs regenerates it and compares line for line.
//
// Every plasticity-off case of tests/traces/ as the arrays a FixedNetwork
// steps: N neurons and S synapses, the time step, the run, whether the
// trace keeps spiking steps only, the trace's header line verbatim, the
// neurons as built (every field), the synapses in the CSR order, and the
// drive as runs of equal steps, (count, currents). plasticity-on is not
// here: a FixedNetwork has no plasticity.
//
// Included by #[path] with #[rustfmt::skip] on the `mod frozen;` line, so
// rustfmt leaves it as written: by tests/traces.rs, and by firmware, since
// it needs only core and neuralos-snn. One allow, builtin: dead_code, since
// an includer reads only the constants it needs.
#![allow(dead_code)]
";

/// The head of the library's frozen file, `tests/traces/frozen.rs`: what
/// it is, how it is made and kept, and its one allow (`dead_code`: an
/// includer reads only the constants it needs). The allow is an inner
/// attribute, so that file is included as a module (`#[path]`), not by
/// `include!`.
///
/// Provisional until the pub walk.
#[must_use]
pub fn preamble() -> &'static str {
    PREAMBLE
}

/// One `pub mod name { … }`, its last newline included: `N`, `S`,
/// `DT_US`, `STEPS`, `SPIKES_ONLY`, `HEADER` (verbatim), `NEURONS` (every
/// field, as given, before the first step), `SYNAPSES` (as given: the
/// delivery order, which [`FixedSynapse::from_network`] gives as the
/// CSR's) and `DRIVE`, runs of equal steps, `(count, currents)`.
///
/// Provisional until the pub walk.
///
/// # Panics
///
/// When a run of `drive` does not hold one current per neuron.
#[must_use]
#[allow(clippy::too_many_arguments)] // one argument per constant of the module
pub fn module(
    name: &str,
    neurons: &[LIFNeuron],
    synapses: &[FixedSynapse],
    dt_us: u32,
    header: &str,
    steps: u32,
    spikes_only: bool,
    drive: &[(u32, Vec<i16>)],
) -> String {
    assert!(
        drive
            .iter()
            .all(|(_, currents)| currents.len() == neurons.len()),
        "one current per neuron in every run of the drive"
    );
    let mut out = format!("pub mod {name} {{\n");
    out.push_str(
        "    use neuralos_snn::{FixedSynapse, LIFNeuron, NeuronType, VoltageResolution};\n\n",
    );
    out.push_str(&format!("    pub const N: usize = {};\n", neurons.len()));
    out.push_str(&format!("    pub const S: usize = {};\n", synapses.len()));
    out.push_str(&format!("    pub const DT_US: u32 = {dt_us};\n"));
    out.push_str(&format!("    pub const STEPS: u32 = {steps};\n"));
    out.push_str(&format!(
        "    pub const SPIKES_ONLY: bool = {spikes_only};\n"
    ));
    out.push_str(&format!("    pub const HEADER: &str = {header:?};\n"));
    out.push_str("    pub const NEURONS: [LIFNeuron; N] = [\n");
    for neuron in neurons {
        out.push_str(&format!("        {},\n", neuron_literal(neuron)));
    }
    out.push_str("    ];\n");
    if synapses.is_empty() {
        out.push_str("    pub const SYNAPSES: [FixedSynapse; S] = [];\n");
    } else {
        out.push_str("    pub const SYNAPSES: [FixedSynapse; S] = [\n");
        for s in synapses {
            out.push_str(&format!(
                "        FixedSynapse {{ pre: {}, post: {}, pulse_ua: {} }},\n",
                s.pre, s.post, s.pulse_ua
            ));
        }
        out.push_str("    ];\n");
    }
    out.push_str("    pub const DRIVE: &[(u32, [i16; N])] = &[\n");
    for (count, currents) in drive {
        let currents: Vec<String> = currents.iter().map(i16::to_string).collect();
        out.push_str(&format!("        ({count}, [{}]),\n", currents.join(", ")));
    }
    out.push_str("    ];\n}\n");
    out
}

/// `for_each_frozen!`, which applies a caller's macro to every module
/// named here, in this order, so no list is kept by hand; then its
/// `pub(crate) use`.
///
/// Provisional until the pub walk.
#[must_use]
pub fn tail(modules: &[String]) -> String {
    let mut out = String::from(
        "/// Applies the caller's macro to every frozen case, in file order.\n\
         macro_rules! for_each_frozen {\n    ($m:ident) => {\n",
    );
    for module in modules {
        out.push_str(&format!("        $m!({module});\n"));
    }
    out.push_str("    };\n}\npub(crate) use for_each_frozen;\n");
    out
}

/// A neuron as a struct literal, every field by name. The pattern lists
/// every field too, so a field added to `LIFNeuron` fails to compile here
/// until the freezer writes it.
fn neuron_literal(n: &LIFNeuron) -> String {
    let LIFNeuron {
        id,
        neuron_type,
        membrane_potential,
        resting_potential,
        threshold,
        reset_potential,
        voltage_resolution,
        tau_membrane_us,
        tau_refractory_us,
        refractory_time_us,
        last_update_time_us,
        last_spike_time_us,
        synaptic_current_ua,
        capacitance_pf,
        resistance_mohm,
        noise_amplitude_ua,
        adaptation_current_ua,
    } = n;
    format!(
        "LIFNeuron {{ id: {id}, neuron_type: NeuronType::{neuron_type:?}, \
         membrane_potential: {membrane_potential}, resting_potential: {resting_potential}, \
         threshold: {threshold}, reset_potential: {reset_potential}, \
         voltage_resolution: VoltageResolution::{voltage_resolution:?}, \
         tau_membrane_us: {tau_membrane_us}, tau_refractory_us: {tau_refractory_us}, \
         refractory_time_us: {refractory_time_us}, last_update_time_us: {last_update_time_us}, \
         last_spike_time_us: {last_spike_time_us}, synaptic_current_ua: {synaptic_current_ua}, \
         capacitance_pf: {capacitance_pf}, resistance_mohm: {resistance_mohm}, \
         noise_amplitude_ua: {noise_amplitude_ua}, adaptation_current_ua: {adaptation_current_ua} }}"
    )
}
