//! NIR fixture tests — the reference-emitted documents of
//! `tests/nir_fixtures/` (generated by `tools/gen_nir_fixtures.py`
//! from the pinned clone `nir-ref/` @ 7883c3c…) drive the public
//! import path. Positive fixtures are the reference's OWN `to_dict()`
//! emissions; negative fixtures are minimal mutations of that
//! emission, one error class each.

use neuralos_snn::nir::{
    nir_export, nir_import, nir_scan, NirBuffers, NirError, NirImport, NirImportOptions,
    NirNode, NirNodeKind, NirNote, EXPORT_VERSION,
};

const CHAIN: &str = include_str!("nir_fixtures/chain.json");
const CHAIN_VRESET: &str = include_str!("nir_fixtures/chain_vreset_absent.json");
const AFFINE: &str = include_str!("nir_fixtures/neg_affine.json");
const UNKNOWN: &str = include_str!("nir_fixtures/neg_unknown_kind.json");
const TAU_ZERO: &str = include_str!("nir_fixtures/neg_tau_zero.json");
const THRESH_ZERO: &str = include_str!("nir_fixtures/neg_threshold_zero_quant.json");
const TAU_DT: &str = include_str!("nir_fixtures/neg_tau_below_dt.json");
const POT_RANGE: &str = include_str!("nir_fixtures/neg_potential_out_of_range.json");
const MISSING_F: &str = include_str!("nir_fixtures/neg_missing_field.json");
const ENDPOINT: &str = include_str!("nir_fixtures/neg_unknown_endpoint.json");
const DUP_EDGE: &str = include_str!("nir_fixtures/neg_duplicate_edge.json");
const RAGGED: &str = include_str!("nir_fixtures/neg_ragged_weight.json");
const PARAM_LEN: &str = include_str!("nir_fixtures/neg_param_length.json");
const MISSING_V: &str = include_str!("nir_fixtures/neg_missing_version.json");
const ESCAPED: &str = include_str!("nir_fixtures/neg_escaped_name.json");

fn import_owned(doc: &str) -> Result<NirImport<'_>, NirError<'_>> {
    NirImport::from_json(doc.as_bytes(), NirImportOptions::default())
}

#[test]
fn reference_chain_imports_with_exact_quantization() {
    let scan = nir_scan(CHAIN.as_bytes()).expect("reference emission scans");
    assert_eq!(scan.version, "1.0.0");
    assert_eq!((scan.node_count, scan.edge_count, scan.weight_cells), (4, 3, 3));

    let g = import_owned(CHAIN).expect("reference emission imports");
    assert_eq!(
        g.nodes
            .iter()
            .map(|n| n.name)
            .collect::<Vec<_>>(),
        vec!["input", "linear", "lif", "output"],
        "document order"
    );
    assert_eq!(g.edges, vec![(0, 1), (1, 2), (2, 3)]);

    let lif = g.nodes[2].lif.expect("lif");
    assert_eq!(
        (lif.tau_us, lif.resistance_mohm, lif.leak_q, lif.threshold_q, lif.reset_q),
        (20_000, 100, -70, -55, -80)
    );
    assert_eq!(lif.capacitance_pf, 200, "C = tau/r = 200 pF");
    assert!(!lif.v_reset_defaulted);

    // dyadic weights at absmax 1.0: q = round(w*32767), scale = 1/32767
    let lin = g.nodes[1].linear.expect("linear");
    assert_eq!((lin.rows, lin.cols), (1, 3));
    assert_eq!(g.weights, vec![16384, -32767, 8192]);
    assert!((lin.scale - 1.0 / 32_767.0).abs() < 1e-20);
    assert!(
        lin.max_abs_err > 0.0 && lin.max_abs_err <= lin.scale / 2.0,
        "scale is non-dyadic: bounded loss, recorded"
    );
}

#[test]
fn absent_v_reset_is_reference_semantics_with_note() {
    let scan = nir_scan(CHAIN_VRESET.as_bytes()).unwrap();
    let mut nodes = vec![
        NirNode {
            name: "",
            kind: NirNodeKind::Input,
            shape: [0; 4],
            shape_len: 0,
            lif: None,
            linear: None,
        };
        scan.node_count
    ];
    let mut edges = vec![(0u32, 0u32); scan.edge_count];
    let mut weights = vec![0i16; scan.weight_cells];
    let mut scratch = vec![0f64; scan.weight_cells];
    let mut bufs = NirBuffers {
        nodes: &mut nodes,
        edges: &mut edges,
        weights: &mut weights,
        scratch: &mut scratch,
    };
    let report = nir_import(
        CHAIN_VRESET.as_bytes(),
        NirImportOptions::default(),
        &mut bufs,
    )
    .expect("imports");
    let lif = nodes[2].lif.expect("lif");
    assert!(lif.v_reset_defaulted);
    assert_eq!(lif.reset_q, 0);
    assert!(report.notes[NirNote::VResetDefaulted as usize] >= 1);
    assert!(report.notes[NirNote::QuantizationLoss as usize] >= 1, "0.1 is not dyadic");
}

#[test]
fn reference_chain_assembles_and_fires() {
    let g = import_owned(CHAIN).expect("imports");
    let (mut net, enc) = g.build_chain_network().expect("canonical chain");
    assert_eq!(net.neuron_count(), 1);
    assert_eq!((enc.rows(), enc.cols()), (1, 3));

    // feature currents (μA) -> encoder -> net; strong enough drive to
    // cross threshold (deterministic: imported neurons are noise-free)
    let spikes: usize = (0..100)
        .map(|t| {
            let i = net.step(&enc.encode(&[4, 0, 0])).expect("step");
            let _ = t;
            i.len()
        })
        .sum();
    assert!(spikes > 0, "the imported chain must actually spike");
}


#[test]
fn reference_chain_export_round_trips() {
    let g = import_owned(CHAIN).expect("imports");
    let mut out = vec![0u8; 4096];
    let n = nir_export(&g.nodes, &g.edges, &g.weights, g.opts, &mut out).expect("exports");
    out.truncate(n);
    assert!(std::str::from_utf8(&out).unwrap().contains(EXPORT_VERSION));

    // byte-stable
    let mut out2 = vec![0u8; 4096];
    let n2 = nir_export(&g.nodes, &g.edges, &g.weights, g.opts, &mut out2).unwrap();
    assert_eq!(out, out2[..n2]);

    // state-identical re-import
    let g2 = NirImport::from_json(&out, g.opts).expect("re-imports");
    assert_eq!(g2.weights, g.weights);
    let l1 = g.nodes[2].lif.unwrap();
    let l2 = g2.nodes[2].lif.unwrap();
    assert_eq!(
        (l2.tau_us, l2.threshold_q, l2.leak_q, l2.reset_q),
        (l1.tau_us, l1.threshold_q, l1.leak_q, l1.reset_q)
    );
}

#[test]
#[allow(clippy::type_complexity)]
fn negative_fixtures_reject_with_the_named_error() {
    let cases: &[(&str, &str, fn(&NirError) -> bool)] = &[
        ("affine", AFFINE, |e| matches!(e, NirError::UnsupportedNodeKind("Affine"))),
        ("unknown kind", UNKNOWN, |e| matches!(e, NirError::UnsupportedNodeKind("CubaLIF"))),
        ("tau zero", TAU_ZERO, |e| matches!(e, NirError::BadNumber("tau"))),
        (
            "threshold quantizes to 0",
            THRESH_ZERO,
            |e| matches!(e, NirError::ThresholdZero),
        ),
        ("tau below dt", TAU_DT, |e| matches!(e, NirError::TauBelowDt)),
        (
            "potential out of range",
            POT_RANGE,
            |e| matches!(e, NirError::PotentialOutOfRange("v_leak")),
        ),
        ("missing field", MISSING_F, |e| matches!(e, NirError::MissingField("v_threshold"))),
        ("unknown endpoint", ENDPOINT, |e| matches!(e, NirError::UnknownEdgeEndpoint("ghost"))),
        ("duplicate edge", DUP_EDGE, |e| matches!(e, NirError::DuplicateEdge)),
        ("ragged weight", RAGGED, |e| matches!(e, NirError::BadShape("weight"))),
        (
            "param length > 1 names slice 2",
            PARAM_LEN,
            |e| matches!(e, NirError::UnsupportedTopology(_)),
        ),
        ("missing version", MISSING_V, |e| matches!(e, NirError::MissingField("version"))),
        ("escaped name", ESCAPED, |e| matches!(e, NirError::EscapedOrNonAsciiString(_))),
    ];
    assert_eq!(cases.len(), 13);
    for (label, doc, check) in cases {
        let err = import_owned(doc).expect_err(label);
        assert!(check(&err), "{label}: got {err:?}");
    }
}

#[test]
fn non_chain_topology_rejects_at_assembly_only() {
    // duplicate edge fixture is a VALID graph shape-wise? no — dup edge
    // rejects at import. Build a valid-but-not-chain graph instead:
    let doc = "{\"version\":\"1.0.0\",\"node\":{\"type\":\"NIRGraph\",\
\"edges\":[[\"a\",\"b\"]],\"nodes\":{\"a\":{\"type\":\"Input\",\"shape\":[1]},\
\"b\":{\"type\":\"Output\",\"shape\":[1]}}}}";
    let g = import_owned(doc).expect("format layer imports any 4-kind graph");
    assert!(
        g.build_chain_network().is_err(),
        "assembly rejects non-chain topologies loudly"
    );
    // and the raw buffer API never rejects on topology:
    let scan = nir_scan(doc.as_bytes()).unwrap();
    assert_eq!(scan.node_count, 2);
}

// keep NirBuffers in scope as a public-API consumer (the fixture
// suite exercises NirImport; the buffer API is pinned in unit tests)
#[test]
fn buffer_api_consumes_reference_emission() {
    let scan = nir_scan(CHAIN.as_bytes()).unwrap();
    let mut nodes = vec![
        NirNode {
            name: "",
            kind: NirNodeKind::Input,
            shape: [0; 4],
            shape_len: 0,
            lif: None,
            linear: None,
        };
        scan.node_count
    ];
    let mut edges = vec![(0u32, 0u32); scan.edge_count];
    let mut weights = vec![0i16; scan.weight_cells];
    let mut scratch = vec![0f64; scan.weight_cells];
    {
        let mut bufs = NirBuffers {
            nodes: &mut nodes,
            edges: &mut edges,
            weights: &mut weights,
            scratch: &mut scratch,
        };
        let report = nir_import(
            CHAIN.as_bytes(),
            NirImportOptions::default(),
            &mut bufs,
        )
        .expect("imports");
        assert_eq!(report.weight_cells, 3);
        assert!(report.note_count() >= 1, "QuantizationLoss noted (non-dyadic scale)");
    }
    assert_eq!(weights, vec![16384, -32767, 8192]);
}
