//! The compare of `tests/traces/`: every file regenerates line for line
//! from `tests/traces/cases.rs`, every header describes its rows, the
//! board case folds to the bench record, the reference vector matches an
//! unbounded-integer neuron model written here, and no file sits in the
//! directory without a case. Part of the test gate
//! (`cargo test --workspace`); alone,
//! `cargo test -p neuralos-snn --test traces`.
//!
//! A trace that moves is red here. A deliberate move is regenerated by
//! `cargo run -p neuralos-snn --example trace -- write` and committed
//! with a message that says which cases moved and why.

#[path = "traces/cases.rs"]
mod cases;

use cases::{Case, Kind, Rows, CASES, DIR, FORMAT};
use neuralos_snn::{MEMBRANE_MV_MAX, MEMBRANE_MV_MIN};

/// The bench record of the firmware's neuron, `evidence/esp32c3-bringup/
/// README.md`: the spike count, the first spike's step, and the wrapping
/// fold `× 31 + step` over the spike steps, both burst arms.
const BOARD_SPIKES: usize = 147;
const BOARD_FIRST_STEP: u32 = 55;
const BOARD_CHECKSUM: u32 = 0x0b78_b456;

fn read(case: &Case) -> String {
    let path = cases::path(case);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// One parsed row.
struct Row {
    step: u32,
    time_us: u32,
    ids: Vec<u16>,
    membranes: Vec<i16>,
}

fn rows(text: &str) -> Vec<Row> {
    text.lines()
        .skip(1)
        .map(|line| {
            let fields: Vec<&str> = line.split(" | ").collect();
            assert_eq!(fields.len(), 3, "three bar-separated fields: {line:?}");
            let mut head = fields[0].split(' ');
            let mut num = |what: &str| -> u32 {
                head.next()
                    .and_then(|s| s.parse().ok())
                    .unwrap_or_else(|| panic!("{what} in {line:?}"))
            };
            let step = num("step");
            let time_us = num("time_us");
            assert!(head.next().is_none(), "step and time only: {line:?}");
            let ids = fields[1]
                .split_whitespace()
                .map(|s| s.parse().unwrap_or_else(|_| panic!("id in {line:?}")))
                .collect();
            let membranes = fields[2]
                .split_whitespace()
                .map(|s| s.parse().unwrap_or_else(|_| panic!("membrane in {line:?}")))
                .collect();
            Row {
                step,
                time_us,
                ids,
                membranes,
            }
        })
        .collect()
}

/// A header field's value, `key=value`.
fn field<'a>(header: &'a str, key: &str) -> &'a str {
    header
        .split(' ')
        .find_map(|kv| kv.strip_prefix(key).and_then(|v| v.strip_prefix('=')))
        .unwrap_or_else(|| panic!("{key}= in {header:?}"))
}

#[test]
fn every_case_regenerates_line_for_line() {
    for case in CASES {
        let file = read(case);
        let code = cases::render(case);
        if file == code {
            continue;
        }
        let (n, (have, want)) = file
            .lines()
            .map(Some)
            .chain(std::iter::repeat(None))
            .zip(code.lines().map(Some).chain(std::iter::repeat(None)))
            .enumerate()
            .find(|(_, (a, b))| a != b)
            .expect("the texts differ, so some line does");
        panic!(
            "trace {} moved at line {}:\n  file: {}\n  code: {}\nA deliberate move is regenerated by \
             `cargo run -p neuralos-snn --example trace -- write`, committed with the why.",
            case.name,
            n + 1,
            have.unwrap_or("<end>"),
            want.unwrap_or("<end>")
        );
    }
}

#[test]
fn every_header_describes_its_rows() {
    for case in CASES {
        let text = read(case);
        let header = text.lines().next().expect("a header");
        assert!(
            header.starts_with(&format!("# {FORMAT} case={} ", case.name)),
            "{header:?}"
        );
        let n: usize = field(header, "n").parse().expect("n");
        let dt_us: u32 = field(header, "dt_us").parse().expect("dt_us");
        let steps: u32 = field(header, "steps").parse().expect("steps");
        assert_eq!(steps, case.steps, "{}", case.name);
        let rows = rows(&text);
        match case.rows {
            Rows::All => {
                assert_eq!(field(header, "rows"), "all", "{}", case.name);
                assert_eq!(
                    rows.len(),
                    steps as usize,
                    "{}: one row per step",
                    case.name
                );
                assert!(
                    rows.iter().enumerate().all(|(i, r)| r.step as usize == i),
                    "{}: steps in order from 0",
                    case.name
                );
            }
            Rows::Spikes => {
                assert_eq!(field(header, "rows"), "spikes", "{}", case.name);
                assert!(
                    rows.iter().all(|r| !r.ids.is_empty() && r.step < steps),
                    "{}: every row is a spiking step inside the run",
                    case.name
                );
                assert!(
                    rows.windows(2).all(|w| w[0].step < w[1].step),
                    "{}: steps ascend",
                    case.name
                );
            }
        }
        for r in &rows {
            assert_eq!(
                r.time_us,
                r.step * dt_us,
                "{}: time is step × dt",
                case.name
            );
            assert_eq!(
                r.membranes.len(),
                n,
                "{}: one membrane per neuron",
                case.name
            );
            assert!(
                r.ids.windows(2).all(|w| w[0] < w[1]) && r.ids.iter().all(|&id| (id as usize) < n),
                "{}: ids ascend and index a neuron",
                case.name
            );
        }
    }
}

#[test]
fn the_board_case_folds_to_the_bench_record() {
    let case = CASES
        .iter()
        .find(|c| c.name == "one-neuron-board")
        .expect("the board case");
    let rows = rows(&read(case));
    assert!(
        rows.iter().all(|r| r.ids == [0]),
        "every row is a spike of the one neuron"
    );
    assert_eq!(rows.len(), BOARD_SPIKES, "spike count");
    assert_eq!(rows[0].step, BOARD_FIRST_STEP, "first spike step");
    let checksum = rows
        .iter()
        .fold(0u32, |acc, r| acc.wrapping_mul(31).wrapping_add(r.step));
    assert_eq!(checksum, BOARD_CHECKSUM, "the fold of the spike steps");
}

#[test]
fn the_reference_vector_matches_the_neuron_model() {
    // The grid the model clamps to, as the neuron documents it; the
    // crate's constants must agree, loudly, or the oracle is not one.
    const FLOOR_MV: i128 = -100;
    const CEILING_MV: i128 = 50;
    assert_eq!(
        (MEMBRANE_MV_MIN, MEMBRANE_MV_MAX),
        (FLOOR_MV as i16, CEILING_MV as i16)
    );

    let mut seen = 0;
    for case in CASES.iter().filter(|c| matches!(c.kind, Kind::Reference)) {
        seen += 1;
        let cases::Run { net, drive } = (case.build)();
        assert_eq!(
            net.neuron_count(),
            1,
            "{}: the oracle is one neuron",
            case.name
        );
        let n = &net.neurons()[0];
        assert_eq!(n.noise_amplitude_ua, 0, "{}: no noise term", case.name);
        assert_eq!(n.threshold, i16::MAX, "{}: no spike term", case.name);
        assert_eq!(net.synapse_count(), 0, "{}: no synaptic term", case.name);

        let text = read(case);
        let header = text.lines().next().expect("a header");
        let dt_us: i128 = field(header, "dt_us").parse().expect("dt_us");
        let s = i128::from(n.voltage_resolution.scale());
        let rest = i128::from(n.resting_potential);
        let r = i128::from(n.resistance_mohm);
        let tau = i128::from(n.tau_membrane_us);
        let mut v = i128::from(n.membrane_potential);

        // The membrane equation with no width limit anywhere: the same
        // arithmetic the neuron documents, in i128, which cannot overflow,
        // with truncating division at the two places the neuron divides.
        for row in rows(&text) {
            assert!(
                row.ids.is_empty(),
                "{}: no spike in a reference vector",
                case.name
            );
            let input = i128::from(drive(row.step)[0]);
            let dt_over_tau = (dt_us * 1000) / tau;
            let leak = rest - v;
            let current = (input * r * s) / 1000;
            let delta = (dt_over_tau * (leak + current)) / 1000;
            v = (v + delta).clamp(FLOOR_MV * s, CEILING_MV * s);
            assert_eq!(
                i128::from(row.membranes[0]),
                v,
                "{} step {}: the neuron and the model part",
                case.name,
                row.step
            );
        }
    }
    assert_eq!(seen, 1, "one reference vector, the neuron");
}

#[test]
fn no_file_without_a_case() {
    let mut orphans: Vec<String> = std::fs::read_dir(DIR)
        .expect("the directory")
        .map(|e| {
            e.expect("an entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| name.ends_with(".trace"))
        .filter(|name| !CASES.iter().any(|c| format!("{}.trace", c.name) == *name))
        .collect();
    orphans.sort();
    assert!(orphans.is_empty(), "files without a case: {orphans:?}");
}
